### ISSUE TITLE
Can't import every module

### ISSUE THREAD

**Issue by LachlanGray** [AlexanderFabisch/distance3d#29]
Hello, 

I installed distance3d , which looks awesome by the way, from pypi but the only modules that I can import are containment, geometry, mesh, and utils. Python can't seem to import the other modules though. 

Have I done something wrong? Sorry if I missed something

Thank you

**Comment by AlexanderFabisch** [comment]
Hi @LachlanGray ,

thanks for reporting. It seems like I actually forgot to push the release 0.4.0 to PyPI. So the documentation and PyPI are out of sync. I don't know how this could happen. I will publish 0.4.0 in a few minutes.

**Comment by AlexanderFabisch** [comment]
There is version 0.4.0 on PyPi now: https://pypi.org/project/distance3d/#history

I hope everything works fine. Otherwise please let me know!

**Comment by LachlanGray** [comment]
Amazing, thank you! Looking forward to trying this out
